= Flake8 Alphabetize
:tox: preamble

Alphabetize is a https://flake8.pycqa.org/en/latest/[Flake8] plugin for checking the
order of `import` statements and the `__all__` list. It is designed to work well with
the https://black.readthedocs.io/en/stable/index.html[black] formatting tool, in that
black never alters the Abstract Syntax Tree (AST), while Alphabetize is *only*
interested in the AST, and so the two tools never conflict. Alphabetise is released
under the https://unlicense.org[Unlicense]. It is tested on Python 3.6+.

image::https://github.com/tlocke/flake8-alphabetize/workflows/flake8-alphabetise/badge.svg[Build Status]


== Installation

* Create a virtual environment: `python3 -m venv venv`
* Activate it: `source venv/bin/activate`
* Install: `pip install flake8-alphabetize`


== Examples

Say we have a Python file:

.myfile.py
[source,python]
----
from datetime import time, date

print(time(9, 39), date(2021, 4, 11))
----

by running the command `flake8` we'll get:

----
myfile.py:1:1: AZ200 Imported names are in the wrong order. Should be date, time
----


We can tell Alphabetize what the package name is, and then it'll know that its imports
should be in group at the bottom of the imports. Here's an example:

.myfile.py
[source,python]
----
import uuid

from myapp import myfunc

print(uuid.UUID4(), myfunc())
----

by running the command `flake8 --application-names myapp` we won't get any
errors.


== Usage

As you use Flake8 in the normal way, Alphabetize will report errors using the following
codes:

.Error Codes
|===
| Code | Error Type

| AZ100
| Import statements are in the wrong order

| AZ200
| The names in the `import from` are in the wrong order

| AZ300
| Two `import from` statements must be combined.
|===


Alphabetize follows the 'black' formatter's uncompromising approach and so there's only
one configuration option which is `application-names`. This is a comma-separated list
of top-level, package names that are to be treated as application imports, eg. 'myapp'.
Since Alphabetize is a Flake8 plugin, this configuration option is set using
https://flake8.pycqa.org/en/latest/user/configuration.html[Flake8 configuration].


== Rules

Here are the ordering rules that Alphabetize follows:

* The special case `pass:macros[from __future__]` import comes first.

* Imports from the standard library come next, followed by third party imports,
  followed by application imports.

* Relative imports are assumed to be application imports.

* The standard library group has `import` statements first (in alphabetical order),
  followed by `from import` statements (in alphabetical order).

* The third party group is further grouped by library name. Then each library subgroup
  has `import` statements first (in alphabetical order), followed by `from import`
  statements (in alphabetical order).

* The application group is further grouped by import level, with absolute imports first
  and then relative imports of increasing level. Within each level, the imports should
  be ordered by library name. Then each library subgroup has `import` statements first
  (in alphabetical order), followed by `from import` statements (in alphabetical order).

* `from import` statements for the same library must be combined.

* Alphabetize only looks at imports at the module level, any imports within the code
  are ignored.


== Doing A Release Of Alphabetize

Run `tox` to make sure all tests pass, then update the release notes, then do:

....
git tag -a x.y.z -m "version x.y.z"
rm -r build
rm -r dist
python setup.py sdist bdist_wheel
for f in dist/*; do gpg --detach-sign -a $f; done
twine upload dist/*
....


== Release Notes

=== Version 0.0.11, 2021-04-11

* Order application imports by import level, absolute imports at the top.


=== Version 0.0.10, 2021-04-11

* Fix bug where potentially fails with > 2 imports.


=== Version 0.0.9, 2021-04-11

* There's a clash of option names, so now application imports can now be identified by
  setting the `application-names` configuration option.


=== Version 0.0.8, 2021-04-11

* Application imports can now be identified by setting the `application-package-names`
  configuration option.


=== Version 0.0.7, 2021-04-10

* Import of `\_\_future\_\_`. Should always be first.


=== Version 0.0.6, 2021-04-10

* Third party libraries should be grouped by top-level name.


=== Version 0.0.5, 2021-04-10

* Take into account whether a module is in the standard library or not.


=== Version 0.0.4, 2021-04-10

* Make entry point AZ instead of ALP.


=== Version 0.0.3, 2021-04-10

* Check the order within `from` `import` statements.


=== Version 0.0.2, 2021-04-09

* Partially support `from` `import` statements.


=== Version 0.0.1, 2021-04-09

* Now partially supports `import` statements.


=== Version 0.0.0, 2021-04-09

* Initial release. Doesn't do much at this stage.
